#include maps\_anim;
main()
{
    // Autogenerated by AnimSounds. Threaded off so that it can be placed before _load( has to create level.scr_notetrack first ).
    thread init_animsounds();
}

init_animsounds()
{
    waittillframeend;
	addOnStart_animSound( "sdv02_pilot", "stealth_kill", "scn_oilrig_npc_waterkill" ); 
	addOnStart_animSound( "player_rig", "player_stealth_kill", "scn_oilrig_plr_waterkill" );     

}
