// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch( codescripts\character::get_random_character(3) )
	{
	case 0:
		character\mp_character_airborne_lmg::main();
		break;
	case 1:
		character\mp_character_airborne_lmg_b::main();
		break;
	case 2:
		character\mp_character_airborne_lmg_c::main();
		break;
	}
}

precache()
{
	character\mp_character_airborne_lmg::precache();
	character\mp_character_airborne_lmg_b::precache();
	character\mp_character_airborne_lmg_c::precache();
}
