// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{

	switch( codescripts\character::get_random_character(3) )
	{
	case 0:
		character\mp_character_opforce_arctic_shotgun::main();
		break;
	case 1:
		character\mp_character_opforce_arctic_shotgun_b::main();
		break;
	case 2:
		character\mp_character_opforce_arctic_shotgun_c::main();
		break;
	}
}

precache()
{
	character\mp_character_opforce_arctic_shotgun::precache();
	character\mp_character_opforce_arctic_shotgun_b::precache();
	character\mp_character_opforce_arctic_shotgun_c::precache();
}
