// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_army_b_dmg_a_wht";
	a[1] = "head_army_b_dmg_b_wht";
	a[2] = "head_army_b_dmg_c_wht";
	a[3] = "head_army_d_dmg_a_wht";
	a[4] = "head_army_d_dmg_b_wht";
	a[5] = "head_army_d_dmg_c_wht";
	return a;
}
