// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_slum_civ_male_a";
	a[1] = "head_slum_civ_male_b";
	a[2] = "head_slum_civ_male_c";
	a[3] = "head_slum_civ_male_d";
	a[4] = "head_slum_civ_male_e";
	return a;
}
