// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_opforce_merc_b_hat";
	a[1] = "head_opforce_merc_c";
	a[2] = "head_opforce_merc_d";
	a[3] = "head_opforce_merc_e";
	a[4] = "head_opforce_merc_f";
	return a;
}
