// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_opforce_arab_a";
	a[1] = "head_opforce_arab_b";
	a[2] = "head_opforce_arab_c";
	a[3] = "head_opforce_arab_d_hat";
	a[4] = "head_opforce_arab_e";
	return a;
}
