// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_trn_arab_a";
	a[1] = "head_trn_arab_b";
	a[2] = "head_trn_arab_c";
	a[3] = "head_trn_arab_d";
	a[4] = "head_trn_arab_e";
	a[5] = "head_trn_arab_f";
	return a;
}
