// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "head_airborne_a";
	a[1] = "head_airborne_b";
	a[2] = "head_airborne_c";
	a[3] = "head_airborne_d";
	a[4] = "head_airborne_e";
	return a;
}
