// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_enemy_favela_SNPR (1.0 0.25 0.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="body_militia_assault_aa_blk"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "sniper_glint_and_rambo.csv";
	self.team = "axis";
	self.type = "human";
	self.subclass = "militia";
	self.accuracy = 0.15;
	self.health = 150;
	self.secondaryweapon = "";
	self.sidearm = "glock";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 1250.000000, 1024.000000 );
		self setEngagementMaxDist( 1600.000000, 2400.000000 );
	}

	self.weapon = "dragunov";

	switch( codescripts\character::get_random_character(2) )
	{
	case 0:
		character\character_op_militia_sniper::main();
		break;
	case 1:
		character\character_opf_militia_assault_aa_wht::main();
		break;
	}
}

spawner()
{
	self setspawnerteam("axis");
}

precache()
{
	character\character_op_militia_sniper::precache();
	character\character_opf_militia_assault_aa_wht::precache();

	precacheItem("dragunov");
	precacheItem("glock");
	precacheItem("fraggrenade");

	//----------------
	maps\_rambo::main();
maps\_sniper_glint::main();
	//----------------
}
