// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_mi17::main( "vehicle_mi17_woodland_fly_cheap" );
	maps\_truck::main( "vehicle_pickup_roobars" );
	common_scripts\_destructible_types_anim_airconditioner::main();
}
