// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_btr80::main( "vehicle_btr80" );
	maps\_btr80::main( "vehicle_btr80_low" );
	maps\_mi17::main( "vehicle_mi17_woodland_fly_cheap" );
	maps\_mi28::main( "vehicle_mi-28_flying_low" );
	maps\_mig29::main( "vehicle_mig29_low" );
	common_scripts\_destructible_types_anim_light_fluo_on::main();
}
