// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_littlebird::main( "vehicle_little_bird_bench" );
	maps\animated_models\foliage_pacific_tropic_shrub01::main();
	maps\animated_models\foliage_tree_palm_tall_2::main();
	maps\animated_models\jeepride_shrubgroup_02_anim::main();
}
