// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_coupe::main( "vehicle_coupe_gold_destructible" );
	maps\_coupe::main( "vehicle_coupe_gray_destructible" );
	maps\_luxurysedan::main( "vehicle_luxurysedan_2009_viewmodel" );
	maps\_van::main( "vehicle_uaz_van" );
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_motorcycle_02::main();
}
