// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_f15::main( "vehicle_f15" );
	maps\_littlebird_player::main( "vehicle_little_bird_bench" );
	maps\_littlebird::main( "vehicle_little_bird_armed" );
	maps\_littlebird::main( "vehicle_little_bird_bench" );
	common_scripts\_destructible_types_anim_light_fluo_on::main();
	common_scripts\_destructible_types_anim_lockers::main();
}
