// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_mi17::main( "vehicle_mi17_woodland_fly_cheap" );
	maps\_mi28::main( "vehicle_mi-28_flying" );
	maps\_ucav::main( "vehicle_ucav" );
	
	precachemodel( "coop_bridge_rappelrope" );
	PrecacheRumble( "so_bridge_collapse" );
}
