// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_apache::main( "vehicle_apache" );
	maps\_blackhawk::main( "vehicle_blackhawk_low" );
	maps\_f15::main( "vehicle_f15" );
	maps\_humvee::main( "vehicle_hummer", "hummer_physics" );
	maps\_pavelow::main( "vehicle_pavelow" );
}
