// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_airport_com_a");
	self attach("head_vil_makarov", "", true);
	self.headModel = "head_vil_makarov";
	self.voice = "seal";
}

precache()
{
	precacheModel("body_airport_com_a");
	precacheModel("head_vil_makarov");
}
