// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_desert_tf141_lmg");
	codescripts\character::attachHead( "alias_tf141_heads_desert", xmodelalias\alias_tf141_heads_desert::main() );
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_desert_tf141_lmg");
	codescripts\character::precacheModelArray(xmodelalias\alias_tf141_heads_desert::main());
}
