// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_vil_shepherd");
	self attach("head_vil_shepherd", "", true);
	self.headModel = "head_vil_shepherd";
	self.voice = "american";
}

precache()
{
	precacheModel("body_vil_shepherd");
	precacheModel("head_vil_shepherd");
}
