// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_airport_com_b");
	self attach("head_airport_b", "", true);
	self.headModel = "head_airport_b";
	self.voice = "seal";
}

precache()
{
	precacheModel("body_airport_com_b");
	precacheModel("head_airport_b");
}
