// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_opforce_sniper_ghillie");
	self attach("head_opforce_sniper_ghillie", "", true);
	self.headModel = "head_opforce_sniper_ghillie";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_opforce_sniper_ghillie");
	precacheModel("head_opforce_sniper_ghillie");
}
