// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_slum_civ_male_ab");
	codescripts\character::attachHead( "alias_civilian_slum_heads", xmodelalias\alias_civilian_slum_heads::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("body_slum_civ_male_ab");
	codescripts\character::precacheModelArray(xmodelalias\alias_civilian_slum_heads::main());
}
