// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_us_army_casual_a_wht");
	self attach("head_army_welder", "", true);
	self.headModel = "head_army_welder";
	self.voice = "american";
}

precache()
{
	precacheModel("body_us_army_casual_a_wht");
	precacheModel("head_army_welder");
}
