// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_ghost_socom");
	self attach("head_hero_ghost_soccom", "", true);
	self.headModel = "head_hero_ghost_soccom";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_hero_ghost_socom");
	precacheModel("head_hero_ghost_soccom");
}
