// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_work_civ_male_a");
	self attach("head_work_civ_welder", "", true);
	self.headModel = "head_work_civ_welder";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_work_civ_male_a");
	precacheModel("head_work_civ_welder");
}
