// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_slum_civ_male_ab_wht");
	codescripts\character::attachHead( "alias_civilian_slum_heads_wht", xmodelalias\alias_civilian_slum_heads_wht::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("body_slum_civ_male_ab_wht");
	codescripts\character::precacheModelArray(xmodelalias\alias_civilian_slum_heads_wht::main());
}
