// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_shadow_co_smg");
	self attach("head_shadow_co_c", "", true);
	self.headModel = "head_shadow_co_c";
	self.voice = "shadowcompany";
}

precache()
{
	precacheModel("body_shadow_co_smg");
	precacheModel("head_shadow_co_c");
}
