// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_seal_udt_dive_a");
	codescripts\character::attachHead( "alias_seal_udt_heads_dive", xmodelalias\alias_seal_udt_heads_dive::main() );
	self.voice = "seal";
}

precache()
{
	precacheModel("body_seal_udt_dive_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_seal_udt_heads_dive::main());
}
