// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_op_miltia_sniper");
	self attach("head_op_militia_sniper", "", true);
	self.headModel = "head_op_militia_sniper";
	self.voice = "portuguese";
}

precache()
{
	precacheModel("body_op_miltia_sniper");
	precacheModel("head_op_militia_sniper");
}
