// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_ghost");
	self attach("head_hero_ghost_forest", "", true);
	self.headModel = "head_hero_ghost_forest";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_forest_tf141_ghost");
	precacheModel("head_hero_ghost_forest");
}
