// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_urban_civ_male_ac_drone");
	codescripts\character::attachHead( "alias_civilian_urban_heads_wht_drone", xmodelalias\alias_civilian_urban_heads_wht_drone::main() );
	self.voice = "russian";
}

precache()
{
	precacheModel("body_urban_civ_male_ac_drone");
	codescripts\character::precacheModelArray(xmodelalias\alias_civilian_urban_heads_wht_drone::main());
}
