// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_desert_tf141_zodiac");
	self attach("head_hero_price_desert", "", true);
	self.headModel = "head_hero_price_desert";
	self.voice = "seal";
}

precache()
{
	precacheModel("body_desert_tf141_zodiac");
	precacheModel("head_hero_price_desert");
}
