// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_ally_arab_trn_assault_a");
	codescripts\character::attachHead( "alias_trn_arab_heads", xmodelalias\alias_trn_arab_heads::main() );
	self.voice = "arab";
}

precache()
{
	precacheModel("body_ally_arab_trn_assault_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_trn_arab_heads::main());
}
