// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_forest_tf141_shotgun");
	self attach("head_tf141_forest_b", "", true);
	self.headModel = "head_tf141_forest_b";
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_forest_tf141_shotgun");
	precacheModel("head_tf141_forest_b");
}
