// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_militia_smg_aa_wht");
	codescripts\character::attachHead( "alias_opforce_militia_heads_wht", xmodelalias\alias_opforce_militia_heads_wht::main() );
	self.voice = "portuguese";
}

precache()
{
	precacheModel("body_militia_smg_aa_wht");
	codescripts\character::precacheModelArray(xmodelalias\alias_opforce_militia_heads_wht::main());
}
