// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_tf141_shotgun");
	codescripts\character::attachHead( "alias_tf141_heads_arctic", xmodelalias\alias_tf141_heads_arctic::main() );
	self.voice = "taskforce";
}

precache()
{
	precacheModel("body_tf141_shotgun");
	codescripts\character::precacheModelArray(xmodelalias\alias_tf141_heads_arctic::main());
}
