// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_riot_op_airborne");
	self attach("head_riot_op_airborne", "", true);
	self.headModel = "head_riot_op_airborne";
	self.voice = "russian";
}

precache()
{
	precacheModel("body_riot_op_airborne");
	precacheModel("head_riot_op_airborne");
}
