// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_riot_tf141_arctic");
	self attach("head_riot_tf141_arctic", "", true);
	self.headModel = "head_riot_tf141_arctic";
	self setViewmodel("viewhands_arctic");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("mp_body_riot_tf141_arctic");
	precacheModel("head_riot_tf141_arctic");
	precacheModel("viewhands_arctic");
}
