// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_ally_sniper_ghillie_forest");
	self attach("head_allies_sniper_ghillie_forest", "", true);
	self.headModel = "head_allies_sniper_ghillie_forest";
	self setViewmodel("viewhands_ghillie_forest");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("mp_body_ally_sniper_ghillie_forest");
	precacheModel("head_allies_sniper_ghillie_forest");
	precacheModel("viewhands_ghillie_forest");
}
