// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_army_sniper");
	self attach("head_allies_us_army_sniper", "", true);
	self.headModel = "head_allies_us_army_sniper";
	self setViewmodel("viewhands_sniper_us_army");
	self.voice = "american";
}

precache()
{
	precacheModel("mp_body_army_sniper");
	precacheModel("head_allies_us_army_sniper");
	precacheModel("viewhands_sniper_us_army");
}
