// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_riot_tf141_forest");
	self attach("head_riot_tf141_forest", "", true);
	self.headModel = "head_riot_tf141_forest";
	self setViewmodel("viewhands_tf141");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("mp_body_riot_tf141_forest");
	precacheModel("head_riot_tf141_forest");
	precacheModel("viewhands_tf141");
}
