// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_riot_op_arab");
	self attach("head_riot_op_arab", "", true);
	self.headModel = "head_riot_op_arab";
	self setViewmodel("viewhands_militia");
	self.voice = "arab";
}

precache()
{
	precacheModel("mp_body_riot_op_arab");
	precacheModel("head_riot_op_arab");
	precacheModel("viewhands_militia");
}
