// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_tf141_forest_sniper");
	self attach("head_allies_tf141_forest_sniper", "", true);
	self.headModel = "head_allies_tf141_forest_sniper";
	self setViewmodel("viewhands_sniper_tf141_forest");
	self.voice = "taskforce";
}

precache()
{
	precacheModel("mp_body_tf141_forest_sniper");
	precacheModel("head_allies_tf141_forest_sniper");
	precacheModel("viewhands_sniper_tf141_forest");
}
