// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_op_sniper_ghillie_arctic");
	self attach("head_op_sniper_ghillie_arctic", "", true);
	self.headModel = "head_op_sniper_ghillie_arctic";
	self setViewmodel("viewhands_ghillie_arctic");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_op_sniper_ghillie_arctic");
	precacheModel("head_op_sniper_ghillie_arctic");
	precacheModel("viewhands_ghillie_arctic");
}
