// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_seal_soccom_assault_b");
	codescripts\character::attachHead( "alias_seal_soccom_heads_mp", xmodelalias\alias_seal_soccom_heads_mp::main() );
	self setViewmodel("viewhands_us_army");
	self.voice = "american";
}

precache()
{
	precacheModel("mp_body_seal_soccom_assault_b");
	codescripts\character::precacheModelArray(xmodelalias\alias_seal_soccom_heads_mp::main());
	precacheModel("viewhands_us_army");
}
