// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_op_sniper_ghillie_desert");
	self attach("head_op_sniper_ghillie_desert", "", true);
	self.headModel = "head_op_sniper_ghillie_desert";
	self setViewmodel("viewhands_ghillie_desert");
	self.voice = "arab";
}

precache()
{
	precacheModel("mp_body_op_sniper_ghillie_desert");
	precacheModel("head_op_sniper_ghillie_desert");
	precacheModel("viewhands_ghillie_desert");
}
