// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_op_miltia_sniper");
	self attach("head_op_militia_sniper", "", true);
	self.headModel = "head_op_militia_sniper";
	self setViewmodel("viewhands_militia");
	self.voice = "portuguese";
}

precache()
{
	precacheModel("mp_body_op_miltia_sniper");
	precacheModel("head_op_militia_sniper");
	precacheModel("viewhands_militia");
}
