// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("mp_body_op_sniper_ghillie_urban");
	self attach("head_op_sniper_ghillie_urban", "", true);
	self.headModel = "head_op_sniper_ghillie_urban";
	self setViewmodel("viewhands_ghillie_urban");
	self.voice = "russian";
}

precache()
{
	precacheModel("mp_body_op_sniper_ghillie_urban");
	precacheModel("head_op_sniper_ghillie_urban");
	precacheModel("viewhands_ghillie_urban");
}
