// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_fortune_machine::main();
	maps\animated_models\accessories_windsock_wind_medium::main();
	maps\animated_models\ferris_wheel::main();
	maps\animated_models\foliage_tree_river_birch_xl_a::main();
}
