// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_generator::main();
	common_scripts\_destructible_types_anim_light_fluo_on::main();
	common_scripts\_destructible_types_anim_light_fluo_single::main();
	common_scripts\_destructible_types_anim_lockers::main();
	common_scripts\_destructible_types_anim_wallfan::main();
	maps\animated_models\tarp_on_cars::main();
}
