// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_light_fluo_single::main();
	common_scripts\_destructible_types_anim_me_fanceil1_spin::main();
	maps\animated_models\foliage_tree_palm_bushy_3::main();
	maps\animated_models\foliage_tree_river_birch_med_a::main();
	maps\animated_models\foliage_tree_river_birch_xl_a::main();
}
