// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_light_fluo_single::main();
	common_scripts\_destructible_types_anim_wallfan::main();
}
