// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\foliage_red_pine_lg::main();
	maps\animated_models\foliage_red_pine_med::main();
	maps\animated_models\foliage_red_pine_xl::main();
	maps\animated_models\foliage_red_pine_xxl::main();
	maps\animated_models\foliage_tree_grey_oak_xl_a::main();
	maps\animated_models\foliage_tree_river_birch_lg_a::main();
	maps\animated_models\foliage_tree_river_birch_xl_a::main();
}
