// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_light_fluo_on::main();
	common_scripts\_destructible_types_anim_lockers::main();
	common_scripts\_destructible_types_anim_wallfan::main();
	maps\animated_models\accessories_windsock_wind_medium::main();
	maps\animated_models\com_roofvent2::main();
	maps\animated_models\foliage_cod5_tree_pine05_large::main();
	maps\animated_models\foliage_pacific_fern01::main();
}
