// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_airconditioner::main();
	common_scripts\_destructible_types_anim_generator::main();
	common_scripts\_destructible_types_anim_me_fanceil1_spin::main();
	maps\animated_models\foliage_dead_pine_lg::main();
	maps\animated_models\foliage_dead_pine_med::main();
}
