// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	common_scripts\_destructible_types_anim_generator::main();
	common_scripts\_destructible_types_anim_lockers::main();
	maps\animated_models\foliage_tree_birch_red_1::main();
	maps\animated_models\foliage_tree_birch_yellow_1::main();
	maps\animated_models\foliage_tree_river_birch_med_a::main();
	maps\animated_models\foliage_tree_river_birch_xl_a::main();
}
